quarkus.azure-functions.app-name=words-function-1773433596394
quarkus.azure-functions.region=germanywestcentral
quarkus.azure-functions.subscription-id=5ac526de-f44c-475f-8181-59acd5700580
quarkus.azure-functions.runtime.java-version=21
quarkus.http.root-path=/api